### ISSUE TITLE
What should this book be called?

### ISSUE THREAD

**Issue by sckott** [getwilds/guide#1]
Dev guide is kind of what I defaulted to, but I'm not sure this guide is only about developers is it?  We can make it whatever we want I guess. Would it be better to go with "Code Guide" or "Contributor Guide" or something else that's a bigger umbrella?

**Comment by sckott** [comment]
@seankross ?
@vortexing ?

**Comment by seankross** [comment]
"Contributor Guide" is nice, I like a big umbrella.

**Comment by vortexing** [comment]
I like Contributor Guide too. Defines how to contribute regardless of who you are I'd hope. :)

**Comment by sckott** [comment]
Okay, changed to Contributing Guide

also changed repo to `guide` in case of any future name changes to the book we don't have to change the repo name
