### ISSUE TITLE
Candace thought dump

### ISSUE THREAD

**Issue by cansavvy** [getwilds/guide#13]
I'm excited for this! Love contributing guides and things that set ground rules and guidance!! :tada:

I did a little bit of stream of consciousness note taking as I went through the pages. Don't feel the need to use everything I referenced here -- but if its helpful, feel free to scavenge and repurpose any of it. 

## Contributing Page comments: 
- Do you want to have a comment about encouraging transparency? i.e. whenever possible be as public as possible to encourage transparency and to minimize redundant conversations, encourage documentation, etc? 
- Is there any scenario in which Notion should be used? (the answer may be no) 

## Styling Page comments: 
- Doing a self cite here, that this talk of good docs makes me think of this course I wrote a while back (would always love your feedback on that too -- but I know you got other things to do) https://jhudatascience.org/Documentation_and_Usability/ 
- Does it make sense to make a template R package and template Python package GitHub repositories? I find myself copying a lot of the same files and etc and it gets annoying -- maybe it would be more efficient to make this (perhaps later down the road) 
- Side note, would love to have a "dummies guide to VSCode" because I still find it overwhelming and haven't had the time to devote to learn it but I know the people who love it really love it. If such a thing exists later we should totally link it somewhere. 

## Code Review Page comments 
- `interal` -> `internal`
- Glad you used those sources! Hopefully folks find them helpful (I'm always open to us updating and polishing those too). 

## Documentation Page comments 
- Oh the docs and usability course is probably relevant here: https://jhudatascience.org/Documentation_and_Usability/ it comes with template docs made from MkDocs: https://github.com/jhudsl/template-documentation that people can alter for their own software package by following the course 
- Made a reproducible example of docs for python https://github.com/jhudsl/reproducible-python-example and R https://github.com/jhudsl/reproducible-r-example these are describe in the intro to Reproducibility course. 
- Oh yay looking forward to `dasl_template`!!
- This chapter I talk about READMEs: https://jhudatascience.org/Reproducibility_in_Cancer_Informatics/organizing-your-project.html and it includes a template README. Again, just use whatever is useful. 
- Can we think of exemplary documentation packages we would like to hold as a standard? Might be nice to link to. 

## Package versions Page comments 
- I'm admittedly bad at keeping my package version numbers up to date. Any tips for me that you may want to include here? Are there ways to automate this somewhat? 

## Security Page comments 
- Looks like this is still under construction -- what things are maybe gonna be there? I also am not very knowledgeable on this topic but am learning.

**Comment by sckott** [comment]
Thanks @cansavvy !

**Comment by sckott** [comment]
@cansavvy 

## contributing chapter: 

> Do you want to have a comment about encouraging transparency? i.e. whenever possible be as public as possible to encourage transparency and to minimize redundant conversations, encourage documentation, etc?

yeah, i think so, will see about that

> Is there any scenario in which Notion should be used? (the answer may be no)

perhaps if we need to do any planning internally - but i don't think we need to mention it in this guide

## style chapter:
  - thanks, i'll have a look at that course
  - template packages: we could but in my experience it's easier to start from scratch and build up complexity of the package as you go. in R land the `usethis` pkg makes it really easy already, and in python land though I'm not sure
  - good note about vs code. by "dummies guide to VSCode" do you mean specifically for R?

## code review chapter: 
  - thanks for typo fix

## documentation chapter:
  - thanks for those resources, i'll take a look

> Can we think of exemplary documentation packages we would like to hold as a standard? Might be nice to link to.

Good idea, i'll point some out

## package versions: 
> Any tips for me that you may want to include here?

just what's in the section i think https://getwilds.org/guide/maintenance.html#package-versioning

> Are there ways to automate this somewhat?

Not that I know of. The only hard check you'll get is that CRAN won't let you submit a new version of a package with a version that's the same or less than what's on CRAN. I just think about what changes are rolling up into the next version and based on that decide whether its a patch, minor or major release. after a cran release, i'd make sure to bump the version on github to the next patch or just add a dev version, e.g., `1.2.1.91` 

## security chapter

> what things are maybe gonna be there?

not sure yet!

**Comment by cansavvy** [comment]
Sounds reasonable on all accounts! 

> good note about vs code. by "dummies guide to VSCode" do you mean specifically for R?

For R or Python. Just as a person who doesn't use VSCode but has tried to make my own setup several times, it would be really great to have an opinionated and brief guide for how to get started with it. I find the endless options for plugins and add-ons overwhelming.

**Comment by sckott** [comment]
okay, yeah sounds good to link out to something, surely there's something already written
