### ISSUE TITLE
Include anything about the hutch or dasl in WILDS software?

### ISSUE THREAD

**Issue by sckott** [getwilds/guide#14]
@seankross @vortexing @tefirman 

Should we mention anything about the hutch or dasl in the software itself? 

For example, in R packages there's a way to include a company/organization/etc. that's either a copyright holder or funder. At ropensci we did like this https://github.com/ropensci/vcr/blob/main/DESCRIPTION#L21

```
person("rOpenSci", role = "fnd", comment = "https://ropensci.org")
```

And Posit does https://github.com/tidyverse/dplyr/blob/main/DESCRIPTION#L15

```
person("Posit Software, PBC", role = c("cph", "fnd"))
```

I don't know if there's anything formal in Python packaging land along these lines, but surely it could be informally included if we think it's necessary. 

I don't have a strong opinion either way here, but figure it's due diligence to raise the issue. thanks y'all

**Comment by sckott** [comment]
(pinged them in slack)

**Comment by tefirman** [comment]
I think it would be smart to put DaSL maybe as one of the authors, so that people can reach out with questions even after the human authors move on to other orgs. The formal way people do it in python is via the ["pyproject.toml" configuration file of the repo](https://packaging.python.org/en/latest/guides/writing-pyproject-toml/#about-your-project), but you could even just put it in as a "magic attribute" in the \_\_init__.py file (e.g. \_\_credits__ = 'Fred Hutch DaSL').

**Comment by sckott** [comment]
thanks @tefirman !

**Comment by sckott** [comment]
From Taylor: In Python, we could list the WILDS/DaSL email account as one the maintainers ("name" isn't a required field). There's also a bunch places in the URL section that could point to the WILDS/DaSL webpage.

**Comment by seankross** [comment]
I largely agree with everything that's been said. Let's specify Fred Hutch as a funder rather than a copyright holder. Also I would prefer that information is specified in an appropriate config file rather than a code file. I'm actively figuring out the email address situation with Amy.

**Comment by sckott** [comment]
- Use this email for listing DaSL as an author/funder/etc: wilds@fredhutch.org
- R: `person("Fred Hutch Data Science Lab", role = "fnd", email = "wilds@fredhutch.org")`
- Python: `{name = "Fred Hutch Data Science Lab"", email = "wilds@fredhutch.org"}` in the authors block in a pyproject.toml file or other config file
