### ISSUE TITLE
Feedback on licenses

### ISSUE THREAD

**Issue by sckott** [getwilds/guide#17]
@seankross take a look at the new licenses section https://getwilds.org/guide/maintenance.html#licenses and let me know any thoughts.

**Comment by sckott** [comment]
any thoughts on this @seankross ?

**Comment by seankross** [comment]
This is great, nice concise advice. I say ship it (I know it's shipped already). In the future we should however assemble the Python braintrust and solidify our opinions about Python packages. For example, I'm leaning towards saying that any WILDS Python package must have a `pyproject.toml`, but I am not fully convinced yet.

**Comment by sckott** [comment]
thanks @seankross 

regarding python, taylor and I just had a chat about all things python in lakeside yesterday, notes [here](https://github.com/getwilds/guide/issues/19) - please comment there - and we should definitely have a call and discuss python things
