### ISSUE TITLE
Repository metadata

### ISSUE THREAD

**Issue by sckott** [getwilds/guide#22]
WILDS needs consistent metadata across repos within WILDS to be able to improve discovery for users and ourselves via a) github itself, and b) the getwilds website. 

At least for me it's important to be able to add/remove/edit/update metadata programmatically. We may not have a lot of repos now, but when we do we will regret using tooling that's manual only

How to metadata?

- GitHub topics. These are the keywords that are editable on the right hand side of a repo page. 
  - proposal: each major category has a topic and will be included in the topics for each repo. the idea behind the `wilds` prefix to the topics is that topics can be anything, so e.g. a repo could formally be a Dockerfile repo, but have some R code in it - someone may apply a topic like `r` or `rstats`, etc. to that repo in which case we wouldn't know whether this was really a docker repo or an R repo. So repos can have any topics they like but need to have some exact topics we control so that we can easily identify the different types with code instead of humans 
    - `wilds-r`: for an R package
    - `wilds-py`: for a Python package
    - `wilds-docker`: for a Dockerfile, or set of files
    - `wilds-comp`: for a Research Compendia
    - `wilds-wdl`: for a WDL workflow
    - `wilds-nf`: for a Nextflow workflow
  - topics can be changed via the `gh` cli tool using `gh repo edit` with flags `--add-topic`/`--remove-topic` ([docs](https://cli.github.com/manual/gh_repo_edit))
  - topics can be changed via the `/repos/{owner}/{repo}/topics` route with the github api ([docs](https://docs.github.com/en/rest/repos/repos?apiVersion=2022-11-28#replace-all-repository-topics))
- Badges. WILDS repos are required to have badges in their README
  - proposal: Scrape the badges from the README's of each repo
  - right now there is only required badge for status of the repo. as others become required we could scrape those as well. In addition, there's optional badges that could be scraped if we find their information useful, such as a badge related to CRAN or PyPi, or build status, or code coverage, etc.
  - we could use the R package `codemetar`, in particular [extract_badges](https://docs.ropensci.org/codemetar/reference/extract_badges.html) - but there's similar tooling in other languages https://codemeta.github.io/tools/

(optional - but I think is kinda the best way to package up metadata across repos)
- Registry? A machine readable file with all the metadata across all WILDS repos.
  - something like the [ropensci registry](https://github.com/ropensci/roregistry/blob/gh-pages/registry.json) 
  - run the code to generate the registry on a cron schedule so it's constantly being updated
  - creates a machine readable file - available simply via gh-pages of a repo as static json file

**Comment by seankross** [comment]
I agree with this proposal, with a couple of clarifications:

- I want to get rid of "translational analytics analysis" as a category for what's in WILDS and replace it with "[Research Compendia](https://research-compendium.science/)." Let's use `wilds-comp` as the topic tag. @monicagerber are you okay with this?
- Is your vision for the registry that it's automatically maintained?

**Comment by monicagerber** [comment]
Agree!

**Comment by sckott** [comment]
Okay, registry repo is started https://github.com/getwilds/registry - super basic for now

**Comment by sckott** [comment]
@seankross let me know any thoughts on the registry repo above when you get a chance

**Comment by sckott** [comment]
seems done
