### ISSUE TITLE
Fill out Contributing chapter

### ISSUE THREAD

**Issue by sckott** [getwilds/guide#7]
not done yet

**Comment by sckott** [comment]
@seankross  I was going to cover a Code of Conduct in this chapter. Any concerns/thoughts on this? If no strong opinions, I'd just use and cite https://www.contributor-covenant.org/version/2/1/code_of_conduct/ and say all contributors fall under that. Is there a COC that is already applied to DaSL staff?

**Comment by seankross** [comment]
This is DaSL's COC: https://github.com/fhdsl/coc but I think it's more of a document that is supposed to apply to DaSL, rather than a document meant to govern particular repos. I would use the COC you linked.

**Comment by sckott** [comment]
Okay, will do.
